[versions]
agp = "8.13.2"
kotlin = "1.8.10"
coreKtx = "1.8.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
mediapipe = "0.10.9"
camerax = "1.4.0-alpha04"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
mediapipe-solution-core = { group = "com.google.mediapipe", name = "solution-core", version.ref = "mediapipe" }
mediapipe-facemesh = { group = "com.google.mediapipe", name = "facemesh", version.ref = "mediapipe" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "camerax" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
